// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {context} from '../models';

export function ActivateLicenseKey(arg1:string):Promise<wails.ActivationStatusDTO>;

export function GetActivationStatus():Promise<wails.ActivationStatusDTO>;

export function ImportLicenseFile():Promise<wails.ActivationStatusDTO>;

export function Startup(arg1:context.Context):Promise<void>;
