// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicenseKey(arg1) {
  return window['go']['wails']['ActivationBindings']['ActivateLicenseKey'](arg1);
}

export function GetActivationStatus() {
  return window['go']['wails']['ActivationBindings']['GetActivationStatus']();
}

export function ImportLicenseFile() {
  return window['go']['wails']['ActivationBindings']['ImportLicenseFile']();
}

export function Startup(arg1) {
  return window['go']['wails']['ActivationBindings']['Startup'](arg1);
}
