// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAnalysisCandidates(arg1) {
  return window['go']['wails']['Bindings']['AddAnalysisCandidates'](arg1);
}

export function AddAnalyticsServiceWord(arg1, arg2) {
  return window['go']['wails']['Bindings']['AddAnalyticsServiceWord'](arg1, arg2);
}

export function AddCanonicalForm(arg1, arg2) {
  return window['go']['wails']['Bindings']['AddCanonicalForm'](arg1, arg2);
}

export function AddCatalogLinks(arg1, arg2, arg3) {
  return window['go']['wails']['Bindings']['AddCatalogLinks'](arg1, arg2, arg3);
}

export function AddChannelLinks(arg1) {
  return window['go']['wails']['Bindings']['AddChannelLinks'](arg1);
}

export function AnalyzeCanonicalKeywords() {
  return window['go']['wails']['Bindings']['AnalyzeCanonicalKeywords']();
}

export function AssignAccountProxy(arg1, arg2) {
  return window['go']['wails']['Bindings']['AssignAccountProxy'](arg1, arg2);
}

export function BulkImportCanonicalKeywords(arg1, arg2) {
  return window['go']['wails']['Bindings']['BulkImportCanonicalKeywords'](arg1, arg2);
}

export function CancelAnalysis() {
  return window['go']['wails']['Bindings']['CancelAnalysis']();
}

export function CancelScheduledDMTask(arg1) {
  return window['go']['wails']['Bindings']['CancelScheduledDMTask'](arg1);
}

export function CheckProxyProfile(arg1) {
  return window['go']['wails']['Bindings']['CheckProxyProfile'](arg1);
}

export function ClassifyCanonicalKeyword(arg1, arg2) {
  return window['go']['wails']['Bindings']['ClassifyCanonicalKeyword'](arg1, arg2);
}

export function ClearCanonicalKeywords(arg1) {
  return window['go']['wails']['Bindings']['ClearCanonicalKeywords'](arg1);
}

export function ClearServiceCanonicalKeywords() {
  return window['go']['wails']['Bindings']['ClearServiceCanonicalKeywords']();
}

export function CloseBackgroundServices(arg1) {
  return window['go']['wails']['Bindings']['CloseBackgroundServices'](arg1);
}

export function ConfigureAnalyticsCollection(arg1, arg2) {
  return window['go']['wails']['Bindings']['ConfigureAnalyticsCollection'](arg1, arg2);
}

export function ConfigureBackups(arg1) {
  return window['go']['wails']['Bindings']['ConfigureBackups'](arg1);
}

export function ConfigureCanonicalAnalytics(arg1) {
  return window['go']['wails']['Bindings']['ConfigureCanonicalAnalytics'](arg1);
}

export function ConfigureImportCandidateExportSelector(arg1) {
  return window['go']['wails']['Bindings']['ConfigureImportCandidateExportSelector'](arg1);
}

export function ConfigureImportFileSelector(arg1) {
  return window['go']['wails']['Bindings']['ConfigureImportFileSelector'](arg1);
}

export function ConfigureLiveStatisticsExportSelector(arg1) {
  return window['go']['wails']['Bindings']['ConfigureLiveStatisticsExportSelector'](arg1);
}

export function ConfigureProduction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['Bindings']['ConfigureProduction'](arg1, arg2, arg3, arg4, arg5);
}

export function ConfigureProxyRouting(arg1, arg2) {
  return window['go']['wails']['Bindings']['ConfigureProxyRouting'](arg1, arg2);
}

export function ConfigureProxyStatus(arg1) {
  return window['go']['wails']['Bindings']['ConfigureProxyStatus'](arg1);
}

export function CreateBackup(arg1) {
  return window['go']['wails']['Bindings']['CreateBackup'](arg1);
}

export function DeleteAnalyticsServiceWord(arg1, arg2) {
  return window['go']['wails']['Bindings']['DeleteAnalyticsServiceWord'](arg1, arg2);
}

export function DeleteCanonicalKeyword(arg1) {
  return window['go']['wails']['Bindings']['DeleteCanonicalKeyword'](arg1);
}

export function DeleteCatalogEntries(arg1, arg2) {
  return window['go']['wails']['Bindings']['DeleteCatalogEntries'](arg1, arg2);
}

export function DeleteLiveTrigger(arg1) {
  return window['go']['wails']['Bindings']['DeleteLiveTrigger'](arg1);
}

export function DeleteProxyProfile(arg1) {
  return window['go']['wails']['Bindings']['DeleteProxyProfile'](arg1);
}

export function ExportAIImportCandidates(arg1, arg2) {
  return window['go']['wails']['Bindings']['ExportAIImportCandidates'](arg1, arg2);
}

export function ExportBackupRecoveryKey(arg1) {
  return window['go']['wails']['Bindings']['ExportBackupRecoveryKey'](arg1);
}

export function ExportLiveDeliveryStatistics(arg1) {
  return window['go']['wails']['Bindings']['ExportLiveDeliveryStatistics'](arg1);
}

export function GetAIImportCandidates(arg1) {
  return window['go']['wails']['Bindings']['GetAIImportCandidates'](arg1);
}

export function GetAIImports() {
  return window['go']['wails']['Bindings']['GetAIImports']();
}

export function GetAccounts() {
  return window['go']['wails']['Bindings']['GetAccounts']();
}

export function GetAnalysisResults() {
  return window['go']['wails']['Bindings']['GetAnalysisResults']();
}

export function GetAnalysisStatus() {
  return window['go']['wails']['Bindings']['GetAnalysisStatus']();
}

export function GetAnalyticsCollectionHistory(arg1) {
  return window['go']['wails']['Bindings']['GetAnalyticsCollectionHistory'](arg1);
}

export function GetAnalyticsCollectionMetrics() {
  return window['go']['wails']['Bindings']['GetAnalyticsCollectionMetrics']();
}

export function GetAnalyticsCollectionSettings() {
  return window['go']['wails']['Bindings']['GetAnalyticsCollectionSettings']();
}

export function GetAnalyticsCollectionStatus() {
  return window['go']['wails']['Bindings']['GetAnalyticsCollectionStatus']();
}

export function GetAnalyticsServiceWords(arg1) {
  return window['go']['wails']['Bindings']['GetAnalyticsServiceWords'](arg1);
}

export function GetAnalyticsTablePreferences(arg1) {
  return window['go']['wails']['Bindings']['GetAnalyticsTablePreferences'](arg1);
}

export function GetAppSettings() {
  return window['go']['wails']['Bindings']['GetAppSettings']();
}

export function GetBackupStatus() {
  return window['go']['wails']['Bindings']['GetBackupStatus']();
}

export function GetCanonicalAnalyticsStatus() {
  return window['go']['wails']['Bindings']['GetCanonicalAnalyticsStatus']();
}

export function GetCatalog(arg1) {
  return window['go']['wails']['Bindings']['GetCatalog'](arg1);
}

export function GetChannelModeration() {
  return window['go']['wails']['Bindings']['GetChannelModeration']();
}

export function GetChannels() {
  return window['go']['wails']['Bindings']['GetChannels']();
}

export function GetDashboard() {
  return window['go']['wails']['Bindings']['GetDashboard']();
}

export function GetKeywordSettings() {
  return window['go']['wails']['Bindings']['GetKeywordSettings']();
}

export function GetLiveDeliveryStatistics(arg1) {
  return window['go']['wails']['Bindings']['GetLiveDeliveryStatistics'](arg1);
}

export function GetProxyStatus() {
  return window['go']['wails']['Bindings']['GetProxyStatus']();
}

export function GetReplyStatistics(arg1, arg2) {
  return window['go']['wails']['Bindings']['GetReplyStatistics'](arg1, arg2);
}

export function GetStorageMetrics() {
  return window['go']['wails']['Bindings']['GetStorageMetrics']();
}

export function GetTopicComparisonResults() {
  return window['go']['wails']['Bindings']['GetTopicComparisonResults']();
}

export function ImportAIFile(arg1) {
  return window['go']['wails']['Bindings']['ImportAIFile'](arg1);
}

export function JoinCatalogEntry(arg1, arg2) {
  return window['go']['wails']['Bindings']['JoinCatalogEntry'](arg1, arg2);
}

export function LeaveCatalogEntry(arg1, arg2) {
  return window['go']['wails']['Bindings']['LeaveCatalogEntry'](arg1, arg2);
}

export function ListAccountRests() {
  return window['go']['wails']['Bindings']['ListAccountRests']();
}

export function ListCanonicalKeywords(arg1) {
  return window['go']['wails']['Bindings']['ListCanonicalKeywords'](arg1);
}

export function ListProxyProfiles() {
  return window['go']['wails']['Bindings']['ListProxyProfiles']();
}

export function ListScheduledDMTasks() {
  return window['go']['wails']['Bindings']['ListScheduledDMTasks']();
}

export function ListServiceCanonicalKeywords() {
  return window['go']['wails']['Bindings']['ListServiceCanonicalKeywords']();
}

export function ModerateAnalysisCandidate(arg1, arg2, arg3) {
  return window['go']['wails']['Bindings']['ModerateAnalysisCandidate'](arg1, arg2, arg3);
}

export function MoveCanonicalForm(arg1, arg2) {
  return window['go']['wails']['Bindings']['MoveCanonicalForm'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['wails']['Bindings']['OpenFile'](arg1);
}

export function ProductionReady() {
  return window['go']['wails']['Bindings']['ProductionReady']();
}

export function RemoveCanonicalForm(arg1, arg2) {
  return window['go']['wails']['Bindings']['RemoveCanonicalForm'](arg1, arg2);
}

export function ResolveScheduledDMRecipients(arg1) {
  return window['go']['wails']['Bindings']['ResolveScheduledDMRecipients'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['wails']['Bindings']['RestoreBackup'](arg1, arg2);
}

export function ResumeLegacyPausedAccount(arg1) {
  return window['go']['wails']['Bindings']['ResumeLegacyPausedAccount'](arg1);
}

export function RetryCatalogJoin(arg1, arg2) {
  return window['go']['wails']['Bindings']['RetryCatalogJoin'](arg1, arg2);
}

export function RunAnalyticsCollectionNow() {
  return window['go']['wails']['Bindings']['RunAnalyticsCollectionNow']();
}

export function RuntimeStore() {
  return window['go']['wails']['Bindings']['RuntimeStore']();
}

export function SaveAnalyticsTablePreferences(arg1) {
  return window['go']['wails']['Bindings']['SaveAnalyticsTablePreferences'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['wails']['Bindings']['SaveAppSettings'](arg1);
}

export function SaveKeywordSettings(arg1) {
  return window['go']['wails']['Bindings']['SaveKeywordSettings'](arg1);
}

export function SaveProxyProfile(arg1) {
  return window['go']['wails']['Bindings']['SaveProxyProfile'](arg1);
}

export function SaveScheduledDMTask(arg1) {
  return window['go']['wails']['Bindings']['SaveScheduledDMTask'](arg1);
}

export function SelectAndImportAIFile(arg1, arg2, arg3) {
  return window['go']['wails']['Bindings']['SelectAndImportAIFile'](arg1, arg2, arg3);
}

export function SetAccountRole(arg1, arg2) {
  return window['go']['wails']['Bindings']['SetAccountRole'](arg1, arg2);
}

export function SetAnalyticsCollectionInterval(arg1) {
  return window['go']['wails']['Bindings']['SetAnalyticsCollectionInterval'](arg1);
}

export function SetAutomationController(arg1) {
  return window['go']['wails']['Bindings']['SetAutomationController'](arg1);
}

export function SetCanonicalKeywordTrigger(arg1, arg2) {
  return window['go']['wails']['Bindings']['SetCanonicalKeywordTrigger'](arg1, arg2);
}

export function SetChannelTopic(arg1, arg2, arg3) {
  return window['go']['wails']['Bindings']['SetChannelTopic'](arg1, arg2, arg3);
}

export function SetChannelTopics(arg1, arg2, arg3) {
  return window['go']['wails']['Bindings']['SetChannelTopics'](arg1, arg2, arg3);
}

export function SetRootContext(arg1) {
  return window['go']['wails']['Bindings']['SetRootContext'](arg1);
}

export function StartAnalysis(arg1) {
  return window['go']['wails']['Bindings']['StartAnalysis'](arg1);
}

export function StartAnalyticsCollection(arg1) {
  return window['go']['wails']['Bindings']['StartAnalyticsCollection'](arg1);
}

export function StartAutomation() {
  return window['go']['wails']['Bindings']['StartAutomation']();
}

export function StartBackgroundServices() {
  return window['go']['wails']['Bindings']['StartBackgroundServices']();
}

export function StartCanonicalAnalytics(arg1) {
  return window['go']['wails']['Bindings']['StartCanonicalAnalytics'](arg1);
}

export function StartScheduledDMTask(arg1) {
  return window['go']['wails']['Bindings']['StartScheduledDMTask'](arg1);
}

export function StartTopicComparison(arg1) {
  return window['go']['wails']['Bindings']['StartTopicComparison'](arg1);
}

export function StopAnalysis(arg1) {
  return window['go']['wails']['Bindings']['StopAnalysis'](arg1);
}

export function StopAnalyticsCollection() {
  return window['go']['wails']['Bindings']['StopAnalyticsCollection']();
}

export function StopAutomation() {
  return window['go']['wails']['Bindings']['StopAutomation']();
}

export function StopCanonicalAnalytics() {
  return window['go']['wails']['Bindings']['StopCanonicalAnalytics']();
}

export function StopOperations(arg1) {
  return window['go']['wails']['Bindings']['StopOperations'](arg1);
}

export function StopScheduledDMTask(arg1) {
  return window['go']['wails']['Bindings']['StopScheduledDMTask'](arg1);
}

export function SyncCanonicalTriggers() {
  return window['go']['wails']['Bindings']['SyncCanonicalTriggers']();
}

export function ToggleCatalogEntry(arg1, arg2, arg3) {
  return window['go']['wails']['Bindings']['ToggleCatalogEntry'](arg1, arg2, arg3);
}

export function ToggleChannelActive(arg1, arg2) {
  return window['go']['wails']['Bindings']['ToggleChannelActive'](arg1, arg2);
}
