// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {context} from '../models';
import {domain} from '../models';
import {runtimeconfig} from '../models';
import {usecase} from '../models';

export function AddAnalysisCandidates(arg1:Array<wails.AnalysisCandidateRefDTO>):Promise<number>;

export function AddAnalyticsServiceWord(arg1:string,arg2:string):Promise<void>;

export function AddCanonicalForm(arg1:string,arg2:string):Promise<void>;

export function AddCatalogLinks(arg1:string,arg2:string,arg3:string):Promise<Array<wails.CatalogEntryDTO>>;

export function AddChannelLinks(arg1:string):Promise<Array<wails.ManagedChannelDTO>>;

export function AnalyzeCanonicalKeywords():Promise<wails.CanonicalAnalysisResultDTO>;

export function AssignAccountProxy(arg1:string,arg2:string):Promise<wails.AccountDTO>;

export function BulkImportCanonicalKeywords(arg1:Array<wails.CanonicalImportEntryDTO>,arg2:string):Promise<wails.CanonicalBulkImportResultDTO>;

export function CancelAnalysis():Promise<void>;

export function CancelScheduledDMTask(arg1:string):Promise<void>;

export function CheckProxyProfile(arg1:string):Promise<wails.ProxyProfileDTO>;

export function ClassifyCanonicalKeyword(arg1:string,arg2:string):Promise<void>;

export function ClearCanonicalKeywords(arg1:string):Promise<void>;

export function ClearServiceCanonicalKeywords():Promise<void>;

export function CloseBackgroundServices(arg1:context.Context):Promise<void>;

export function ConfigureAnalyticsCollection(arg1:wails.AnalyticsCollectionScheduler,arg2:domain.AnalyticsSchedulerStore):Promise<void>;

export function ConfigureBackups(arg1:wails.BackupRuntime):Promise<void>;

export function ConfigureCanonicalAnalytics(arg1:wails.CanonicalAnalyticsService):Promise<void>;

export function ConfigureImportCandidateExportSelector(arg1:wails.ImportCandidateExportSelector):Promise<void>;

export function ConfigureImportFileSelector(arg1:wails.ImportFileSelector):Promise<void>;

export function ConfigureLiveStatisticsExportSelector(arg1:wails.LiveStatisticsExportSelector):Promise<void>;

export function ConfigureProduction(arg1:wails.StorageMetricsProvider,arg2:wails.AnalyticsService,arg3:wails.AIImportService,arg4:wails.FileOpener,arg5:Array<wails.ScoutHistorySyncer>):Promise<void>;

export function ConfigureProxyRouting(arg1:domain.ProxyProfileRepository,arg2:wails.ProxyRouteRegistry):Promise<void>;

export function ConfigureProxyStatus(arg1:wails.ProxyStatusProvider):Promise<void>;

export function CreateBackup(arg1:string):Promise<wails.BackupDTO>;

export function DeleteAnalyticsServiceWord(arg1:string,arg2:string):Promise<void>;

export function DeleteCanonicalKeyword(arg1:string):Promise<void>;

export function DeleteCatalogEntries(arg1:string,arg2:Array<string>):Promise<Array<wails.CatalogEntryDTO>>;

export function DeleteLiveTrigger(arg1:string):Promise<void>;

export function DeleteProxyProfile(arg1:string):Promise<void>;

export function ExportAIImportCandidates(arg1:string,arg2:string):Promise<string>;

export function ExportBackupRecoveryKey(arg1:string):Promise<void>;

export function ExportLiveDeliveryStatistics(arg1:wails.LiveDeliveryExportRequestDTO):Promise<string>;

export function GetAIImportCandidates(arg1:string):Promise<Array<wails.AnalysisCandidateDTO>>;

export function GetAIImports():Promise<Array<wails.AIImportDTO>>;

export function GetAccounts():Promise<Array<wails.AccountDTO>>;

export function GetAnalysisResults():Promise<wails.AnalysisResultsDTO>;

export function GetAnalysisStatus():Promise<wails.AnalysisStatusDTO>;

export function GetAnalyticsCollectionHistory(arg1:number):Promise<Array<wails.AnalyticsRunDTO>>;

export function GetAnalyticsCollectionMetrics():Promise<wails.AnalyticsMetricsDTO>;

export function GetAnalyticsCollectionSettings():Promise<wails.AnalyticsSettingsDTO>;

export function GetAnalyticsCollectionStatus():Promise<wails.AnalyticsCollectionStatusDTO>;

export function GetAnalyticsServiceWords(arg1:string):Promise<Array<string>>;

export function GetAnalyticsTablePreferences(arg1:string):Promise<wails.AnalyticsTablePreferenceDTO>;

export function GetAppSettings():Promise<wails.AppSettingsDTO>;

export function GetBackupStatus():Promise<wails.BackupDTO>;

export function GetCanonicalAnalyticsStatus():Promise<wails.AnalyticsCollectionStatusDTO>;

export function GetCatalog(arg1:string):Promise<Array<wails.CatalogEntryDTO>>;

export function GetChannelModeration():Promise<Array<wails.ChannelModerationDTO>>;

export function GetChannels():Promise<Array<wails.ManagedChannelDTO>>;

export function GetDashboard():Promise<wails.DashboardDTO>;

export function GetKeywordSettings():Promise<wails.KeywordSettingsDTO>;

export function GetLiveDeliveryStatistics(arg1:wails.LiveDeliveryQueryDTO):Promise<wails.LiveDeliveryPageDTO>;

export function GetProxyStatus():Promise<wails.ProxyStatusDTO>;

export function GetReplyStatistics(arg1:string,arg2:string):Promise<wails.ReplyStatisticsDTO>;

export function GetStorageMetrics():Promise<wails.StorageMetricsDTO>;

export function GetTopicComparisonResults():Promise<Array<wails.TopicSummaryDTO>>;

export function ImportAIFile(arg1:wails.AIImportRequestDTO):Promise<wails.AIImportDTO>;

export function JoinCatalogEntry(arg1:string,arg2:string):Promise<Array<wails.CatalogEntryDTO>>;

export function LeaveCatalogEntry(arg1:string,arg2:string):Promise<Array<wails.CatalogEntryDTO>>;

export function ListAccountRests():Promise<Array<wails.AccountRestDTO>>;

export function ListCanonicalKeywords(arg1:string):Promise<Array<wails.CanonicalKeywordDTO>>;

export function ListProxyProfiles():Promise<Array<wails.ProxyProfileDTO>>;

export function ListScheduledDMTasks():Promise<Array<wails.ScheduledDMTaskDTO>>;

export function ListServiceCanonicalKeywords():Promise<Array<wails.CanonicalKeywordDTO>>;

export function ModerateAnalysisCandidate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveCanonicalForm(arg1:string,arg2:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function ProductionReady():Promise<void>;

export function RemoveCanonicalForm(arg1:string,arg2:string):Promise<wails.CanonicalKeywordDTO>;

export function ResolveScheduledDMRecipients(arg1:string):Promise<Array<wails.ScheduledDMRecipientDTO>>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function ResumeLegacyPausedAccount(arg1:string):Promise<wails.AccountDTO>;

export function RetryCatalogJoin(arg1:string,arg2:string):Promise<Array<wails.ChannelModerationDTO>>;

export function RunAnalyticsCollectionNow():Promise<wails.AnalyticsRunDTO>;

export function RuntimeStore():Promise<runtimeconfig.Store>;

export function SaveAnalyticsTablePreferences(arg1:wails.AnalyticsTablePreferenceDTO):Promise<void>;

export function SaveAppSettings(arg1:wails.AppSettingsDTO):Promise<wails.AppSettingsDTO>;

export function SaveKeywordSettings(arg1:wails.KeywordSettingsDTO):Promise<wails.KeywordSettingsDTO>;

export function SaveProxyProfile(arg1:wails.ProxyProfileInputDTO):Promise<wails.ProxyProfileDTO>;

export function SaveScheduledDMTask(arg1:wails.ScheduledDMDraftDTO):Promise<wails.ScheduledDMTaskDTO>;

export function SelectAndImportAIFile(arg1:boolean,arg2:string,arg3:string):Promise<wails.AIImportDTO>;

export function SetAccountRole(arg1:string,arg2:string):Promise<wails.AccountDTO>;

export function SetAnalyticsCollectionInterval(arg1:number):Promise<wails.AnalyticsSettingsDTO>;

export function SetAutomationController(arg1:usecase.AutomationController):Promise<void>;

export function SetCanonicalKeywordTrigger(arg1:string,arg2:boolean):Promise<void>;

export function SetChannelTopic(arg1:string,arg2:string,arg3:string):Promise<Array<wails.CatalogEntryDTO>>;

export function SetChannelTopics(arg1:string,arg2:Array<string>,arg3:string):Promise<Array<wails.CatalogEntryDTO>>;

export function SetRootContext(arg1:context.Context):Promise<void>;

export function StartAnalysis(arg1:wails.AnalysisRequestDTO):Promise<wails.AnalysisStatusDTO>;

export function StartAnalyticsCollection(arg1:number):Promise<void>;

export function StartAutomation():Promise<void>;

export function StartBackgroundServices():Promise<void>;

export function StartCanonicalAnalytics(arg1:number):Promise<void>;

export function StartScheduledDMTask(arg1:string):Promise<void>;

export function StartTopicComparison(arg1:wails.TopicComparisonRequestDTO):Promise<wails.AnalysisStatusDTO>;

export function StopAnalysis(arg1:context.Context):Promise<void>;

export function StopAnalyticsCollection():Promise<void>;

export function StopAutomation():Promise<void>;

export function StopCanonicalAnalytics():Promise<void>;

export function StopOperations(arg1:context.Context):Promise<void>;

export function StopScheduledDMTask(arg1:string):Promise<void>;

export function SyncCanonicalTriggers():Promise<void>;

export function ToggleCatalogEntry(arg1:string,arg2:string,arg3:boolean):Promise<Array<wails.CatalogEntryDTO>>;

export function ToggleChannelActive(arg1:string,arg2:boolean):Promise<Array<wails.ManagedChannelDTO>>;
