// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {context} from '../models';

export function ChooseAnotherLicense():Promise<wails.DesktopStartupStatusDTO>;

export function GetDesktopStartupStatus():Promise<wails.DesktopStartupStatusDTO>;

export function RetryStartup():Promise<wails.DesktopStartupStatusDTO>;

export function Startup(arg1:context.Context):Promise<void>;
