// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseAnotherLicense() {
  return window['go']['wails']['StartupBindings']['ChooseAnotherLicense']();
}

export function GetDesktopStartupStatus() {
  return window['go']['wails']['StartupBindings']['GetDesktopStartupStatus']();
}

export function RetryStartup() {
  return window['go']['wails']['StartupBindings']['RetryStartup']();
}

export function Startup(arg1) {
  return window['go']['wails']['StartupBindings']['Startup'](arg1);
}
