// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {context} from '../models';

export function CheckForUpdates():Promise<wails.UpdateStatusDTO>;

export function DownloadUpdate():Promise<wails.UpdateStatusDTO>;

export function GetUpdateStatus():Promise<wails.UpdateStatusDTO>;

export function RestartAndInstallUpdate():Promise<wails.UpdateStatusDTO>;

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
