// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['wails']['UpdateBindings']['CheckForUpdates']();
}

export function DownloadUpdate() {
  return window['go']['wails']['UpdateBindings']['DownloadUpdate']();
}

export function GetUpdateStatus() {
  return window['go']['wails']['UpdateBindings']['GetUpdateStatus']();
}

export function RestartAndInstallUpdate() {
  return window['go']['wails']['UpdateBindings']['RestartAndInstallUpdate']();
}

export function Shutdown() {
  return window['go']['wails']['UpdateBindings']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['wails']['UpdateBindings']['Startup'](arg1);
}
